// <auto-generated />
using System;
using Citas_Medicas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Citas_Medicas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730023659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Citas_Medicas.Modules.Citas.Entities.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.Property<string>("Medico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombrePaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCita")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeguroMedico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
