// <auto-generated />
using System;
using Citas_Medicas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Citas_Medicas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806020035_AgregarMedico")]
    partial class AgregarMedico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Citas_Medicas.Modules.Citas.Entities.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.Property<int>("MedicoId")
                        .HasColumnType("integer");

                    b.Property<string>("NombrePaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCita")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeguroMedico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("Citas_Medicas.Modules.Medicos.Entities.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorarioAtencion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreMedico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroConsultorio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("Citas_Medicas.Modules.Citas.Entities.Cita", b =>
                {
                    b.HasOne("Citas_Medicas.Modules.Medicos.Entities.Medico", "Medico")
                        .WithMany("Citas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Citas_Medicas.Modules.Medicos.Entities.Medico", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
